run_readable_name: "NACC-3B-OS-SFT-ES-0240" # will be used to name the results folder

training_steps: 240

# passed to vllm.LLM, you can use any accepted keyword argument
LLM:
  model: "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/open-r1/ckpt/ckpt_access/qwen25_3B_sft_nacc_inc_oversample_with_earlystopping/checkpoint-240" # can be a path
  tensor_parallel_size: 1 # Number of GPUs used. Passed to vllm.LLM.tensor_parallel_size. 
  gpu_memory_utilization: 0.9 # Fraction of gpu memory reserved for model + attention
  max_model_len: 30000
  distributed_executor_backend: 'mp'
  seed: 1 # seed to initialize RNG for sampling
  enable_lora: false
  # lora_path: # uncomment if want to use lora

# passed to vllm.SamplingParams, you can use any accepted keyword argument
sampling_params:
  n: 5 # Number of sequences to generate per prompt
  temperature: 1 # recommended
  top_p: 1 # consider candidate tokens until the cumulative sum of their probabilities is top_p
  max_tokens: 10000 # maximum number of tokens to generate

prompt:
  system_prompt: "Provide only the final answer in the format: The answer is \\boxed{option_letter}: option_text, with no reasoning."
  template_style: sft

benchmarks:
  results_dir: '/projectnb/vkolagrp/projects/adrd_foundation_model/results/training_curve' # Benchmarks outputs will be saved in this directory
  base_dir: "/projectnb/vkolagrp/projects/adrd_foundation_model/benchmarks" # Base directory for benchmarks
  run_dir: "NACC-3B-OS-SFT-ES" # Run folder
  max_questions: 10000000 # Read at most this many questions from the benchmark
  benchmark_list:
    - '${benchmarks.base_dir}/adni_test/test_cog'
    - '${benchmarks.base_dir}/adni_test/test_pet'
    - '${benchmarks.base_dir}/adni_test/test_etpr'
    - '${benchmarks.base_dir}/adni_test/test_csf'
    - '${benchmarks.base_dir}/brainlat_test/test_cog'
    - '${benchmarks.base_dir}/brainlat_test/test_etpr'
    - '${benchmarks.base_dir}/nacc_test_updated/test_cog'
    - '${benchmarks.base_dir}/nacc_test_updated/test_csf'
    - '${benchmarks.base_dir}/nacc_test_updated/test_dat'
    - '${benchmarks.base_dir}/nacc_test_updated/test_etpr'
    - '${benchmarks.base_dir}/nacc_test_updated/test_np_mixed'
    - '${benchmarks.base_dir}/nacc_test_updated/test_np_one'
    - '${benchmarks.base_dir}/nacc_test_updated/test_pet'
    - '${benchmarks.base_dir}/nifd_test/test_cog'
    - '${benchmarks.base_dir}/nifd_test/test_etpr'
    - '${benchmarks.base_dir}/ppmi_test/test_cog'
    - '${benchmarks.base_dir}/ppmi_test/test_dat'
    - '${benchmarks.base_dir}/ppmi_test/test_etpr'
